// Generated by Haxe 4.1.1

#pragma warning disable 109, 114, 219, 429, 168, 162
namespace invoices {
	public class Invoices : global::haxe.lang.HxObject {
		
		static Invoices() {
			unchecked{
				#line 8 "/my-component/src/invoices/Invoices.hx"
				global::haxe.lang.FieldLookup.addFields(new int[]{957002115}, new string[]{"registerMyMethods"});
			}
		}
		#line default
		
		public Invoices(global::haxe.lang.EmptyObject empty) {
		}
		
		
		public Invoices(global::maglev.MagLev maglev) {
			#line 11 "/my-component/src/invoices/Invoices.hx"
			global::invoices.Invoices.__hx_ctor_invoices_Invoices(this, maglev);
		}
		#line default
		
		protected static void __hx_ctor_invoices_Invoices(global::invoices.Invoices __hx_this, global::maglev.MagLev maglev) {
			#line 12 "/my-component/src/invoices/Invoices.hx"
			__hx_this.maglev = maglev;
			__hx_this.registerMyMethods();
		}
		#line default
		
		public global::maglev.MagLev maglev;
		
		public virtual void registerMyMethods() {
			#line 17 "/my-component/src/invoices/Invoices.hx"
			global::maglev.MagLev bus = this.maglev;
			#line 19 "/my-component/src/invoices/Invoices.hx"
			this.maglev.register("Invoices.CreateInvoice", global::maglev.MagLevFunction.fromFunction(new global::invoices.Invoices_registerMyMethods_19__Fun(bus)));
			#line 30 "/my-component/src/invoices/Invoices.hx"
			this.maglev.register("Invoices.DeleteInvoice", global::maglev.MagLevFunction.fromFunction(new global::invoices.Invoices_registerMyMethods_30__Fun(bus)));
			#line 41 "/my-component/src/invoices/Invoices.hx"
			this.maglev.register("Invoices.ChangeInvoice", global::maglev.MagLevFunction.fromFunction(new global::invoices.Invoices_registerMyMethods_41__Fun(bus)));
			#line 52 "/my-component/src/invoices/Invoices.hx"
			this.maglev.register("Invoices.GetInvoiceSummary", global::maglev.MagLevFunction.fromFunction(new global::invoices.Invoices_registerMyMethods_52__Fun(bus)));
			#line 63 "/my-component/src/invoices/Invoices.hx"
			this.maglev.register("Invoices.GetLineItems", global::maglev.MagLevFunction.fromFunction(new global::invoices.Invoices_registerMyMethods_63__Fun(bus)));
			#line 74 "/my-component/src/invoices/Invoices.hx"
			this.maglev.register("Invoices.AddLineItem", global::maglev.MagLevFunction.fromFunction(new global::invoices.Invoices_registerMyMethods_74__Fun(bus)));
			#line 85 "/my-component/src/invoices/Invoices.hx"
			this.maglev.register("Invoices.ChangeLineItem", global::maglev.MagLevFunction.fromFunction(new global::invoices.Invoices_registerMyMethods_85__Fun(bus)));
			#line 96 "/my-component/src/invoices/Invoices.hx"
			this.maglev.register("Invoices.RemoveLineItem", global::maglev.MagLevFunction.fromFunction(new global::invoices.Invoices_registerMyMethods_96__Fun(bus)));
			#line 107 "/my-component/src/invoices/Invoices.hx"
			this.maglev.register("Invoices.GetInvoicesByClient", global::maglev.MagLevFunction.fromFunction(new global::invoices.Invoices_registerMyMethods_107__Fun(bus)));
			#line 118 "/my-component/src/invoices/Invoices.hx"
			this.maglev.register("Invoices.GetAllInvoices", global::maglev.MagLevFunction.fromFunction(new global::invoices.Invoices_registerMyMethods_118__Fun(bus)));
			#line 129 "/my-component/src/invoices/Invoices.hx"
			this.maglev.register("Invoices.FindInvoiceByNumber", global::maglev.MagLevFunction.fromFunction(new global::invoices.Invoices_registerMyMethods_129__Fun(bus)));
		}
		#line default
		
		public override object __hx_setField(string field, int hash, object @value, bool handleProperties) {
			unchecked {
				#line 8 "/my-component/src/invoices/Invoices.hx"
				switch (hash) {
					case 858513194:
					{
						#line 8 "/my-component/src/invoices/Invoices.hx"
						this.maglev = ((global::maglev.MagLev) (@value) );
						#line 8 "/my-component/src/invoices/Invoices.hx"
						return @value;
					}
					
					
					default:
					{
						#line 8 "/my-component/src/invoices/Invoices.hx"
						return base.__hx_setField(field, hash, @value, handleProperties);
					}
					
				}
				
			}
			#line default
		}
		
		
		public override object __hx_getField(string field, int hash, bool throwErrors, bool isCheck, bool handleProperties) {
			unchecked {
				#line 8 "/my-component/src/invoices/Invoices.hx"
				switch (hash) {
					case 957002115:
					{
						#line 8 "/my-component/src/invoices/Invoices.hx"
						return ((global::haxe.lang.Function) (new global::haxe.lang.Closure(this, "registerMyMethods", 957002115)) );
					}
					
					
					case 858513194:
					{
						#line 8 "/my-component/src/invoices/Invoices.hx"
						return this.maglev;
					}
					
					
					default:
					{
						#line 8 "/my-component/src/invoices/Invoices.hx"
						return base.__hx_getField(field, hash, throwErrors, isCheck, handleProperties);
					}
					
				}
				
			}
			#line default
		}
		
		
		public override object __hx_invokeField(string field, int hash, object[] dynargs) {
			unchecked {
				#line 8 "/my-component/src/invoices/Invoices.hx"
				switch (hash) {
					case 957002115:
					{
						#line 8 "/my-component/src/invoices/Invoices.hx"
						this.registerMyMethods();
						#line 8 "/my-component/src/invoices/Invoices.hx"
						break;
					}
					
					
					default:
					{
						#line 8 "/my-component/src/invoices/Invoices.hx"
						return base.__hx_invokeField(field, hash, dynargs);
					}
					
				}
				
				#line 8 "/my-component/src/invoices/Invoices.hx"
				return null;
			}
			#line default
		}
		
		
		public override void __hx_getFields(global::Array<string> baseArr) {
			#line 8 "/my-component/src/invoices/Invoices.hx"
			baseArr.push("maglev");
			#line 8 "/my-component/src/invoices/Invoices.hx"
			base.__hx_getFields(baseArr);
		}
		#line default
		
	}
}



#pragma warning disable 109, 114, 219, 429, 168, 162
namespace invoices {
	public class Invoices_registerMyMethods_19__Fun : global::haxe.lang.Function {
		
		public Invoices_registerMyMethods_19__Fun(global::maglev.MagLev bus) : base(1, 0) {
			#line 19 "/my-component/src/invoices/Invoices.hx"
			this.bus = bus;
		}
		#line default
		
		public override object __hx_invoke1_o(double __fn_float1, object __fn_dyn1) {
			unchecked {
				#line 19 "/my-component/src/invoices/Invoices.hx"
				global::maglev.MagLevArray args = ( (( __fn_dyn1 == global::haxe.lang.Runtime.undefined )) ? (((global::maglev.MagLevArray) (((object) (__fn_float1) )) )) : (((global::maglev.MagLevArray) (__fn_dyn1) )) );
				global::maglev.MagLevArray data = global::maglev.MagLevArray.create();
				#line 21 "/my-component/src/invoices/Invoices.hx"
				data.push(global::maglev.MagLevString.fromString("_not_implemented_"));
				data.push(global::maglev.MagLevString.fromString("Invoices.CreateInvoice"));
				#line 23 "/my-component/src/invoices/Invoices.hx"
				data.push(global::maglev.MagLevString.fromString("invoices"));
				this.bus.call("MindPowered.Telemetry.Send", data);
				#line 25 "/my-component/src/invoices/Invoices.hx"
				global::maglev.MagLevError err = global::maglev.MagLevError.create(-20000, "You are trying to use the \'Invoices.CreateInvoice\' method but it\'s not quite done yet. Please email support@mindpowered.dev to find out when it will be done.", data);
				global::maglev.MagLevResult result = global::maglev.MagLevResult.fromError(err);
				#line 27 "/my-component/src/invoices/Invoices.hx"
				return result;
			}
			#line default
		}
		
		
		public global::maglev.MagLev bus;
		
	}
}



#pragma warning disable 109, 114, 219, 429, 168, 162
namespace invoices {
	public class Invoices_registerMyMethods_30__Fun : global::haxe.lang.Function {
		
		public Invoices_registerMyMethods_30__Fun(global::maglev.MagLev bus) : base(1, 0) {
			#line 30 "/my-component/src/invoices/Invoices.hx"
			this.bus = bus;
		}
		#line default
		
		public override object __hx_invoke1_o(double __fn_float1, object __fn_dyn1) {
			unchecked {
				#line 30 "/my-component/src/invoices/Invoices.hx"
				global::maglev.MagLevArray args = ( (( __fn_dyn1 == global::haxe.lang.Runtime.undefined )) ? (((global::maglev.MagLevArray) (((object) (__fn_float1) )) )) : (((global::maglev.MagLevArray) (__fn_dyn1) )) );
				global::maglev.MagLevArray data = global::maglev.MagLevArray.create();
				#line 32 "/my-component/src/invoices/Invoices.hx"
				data.push(global::maglev.MagLevString.fromString("_not_implemented_"));
				data.push(global::maglev.MagLevString.fromString("Invoices.DeleteInvoice"));
				#line 34 "/my-component/src/invoices/Invoices.hx"
				data.push(global::maglev.MagLevString.fromString("invoices"));
				this.bus.call("MindPowered.Telemetry.Send", data);
				#line 36 "/my-component/src/invoices/Invoices.hx"
				global::maglev.MagLevError err = global::maglev.MagLevError.create(-20000, "You are trying to use the \'Invoices.DeleteInvoice\' method but it\'s not quite done yet. Please email support@mindpowered.dev to find out when it will be done.", data);
				global::maglev.MagLevResult result = global::maglev.MagLevResult.fromError(err);
				#line 38 "/my-component/src/invoices/Invoices.hx"
				return result;
			}
			#line default
		}
		
		
		public global::maglev.MagLev bus;
		
	}
}



#pragma warning disable 109, 114, 219, 429, 168, 162
namespace invoices {
	public class Invoices_registerMyMethods_41__Fun : global::haxe.lang.Function {
		
		public Invoices_registerMyMethods_41__Fun(global::maglev.MagLev bus) : base(1, 0) {
			#line 41 "/my-component/src/invoices/Invoices.hx"
			this.bus = bus;
		}
		#line default
		
		public override object __hx_invoke1_o(double __fn_float1, object __fn_dyn1) {
			unchecked {
				#line 41 "/my-component/src/invoices/Invoices.hx"
				global::maglev.MagLevArray args = ( (( __fn_dyn1 == global::haxe.lang.Runtime.undefined )) ? (((global::maglev.MagLevArray) (((object) (__fn_float1) )) )) : (((global::maglev.MagLevArray) (__fn_dyn1) )) );
				global::maglev.MagLevArray data = global::maglev.MagLevArray.create();
				#line 43 "/my-component/src/invoices/Invoices.hx"
				data.push(global::maglev.MagLevString.fromString("_not_implemented_"));
				data.push(global::maglev.MagLevString.fromString("Invoices.ChangeInvoice"));
				#line 45 "/my-component/src/invoices/Invoices.hx"
				data.push(global::maglev.MagLevString.fromString("invoices"));
				this.bus.call("MindPowered.Telemetry.Send", data);
				#line 47 "/my-component/src/invoices/Invoices.hx"
				global::maglev.MagLevError err = global::maglev.MagLevError.create(-20000, "You are trying to use the \'Invoices.ChangeInvoice\' method but it\'s not quite done yet. Please email support@mindpowered.dev to find out when it will be done.", data);
				global::maglev.MagLevResult result = global::maglev.MagLevResult.fromError(err);
				#line 49 "/my-component/src/invoices/Invoices.hx"
				return result;
			}
			#line default
		}
		
		
		public global::maglev.MagLev bus;
		
	}
}



#pragma warning disable 109, 114, 219, 429, 168, 162
namespace invoices {
	public class Invoices_registerMyMethods_52__Fun : global::haxe.lang.Function {
		
		public Invoices_registerMyMethods_52__Fun(global::maglev.MagLev bus) : base(1, 0) {
			#line 52 "/my-component/src/invoices/Invoices.hx"
			this.bus = bus;
		}
		#line default
		
		public override object __hx_invoke1_o(double __fn_float1, object __fn_dyn1) {
			unchecked {
				#line 52 "/my-component/src/invoices/Invoices.hx"
				global::maglev.MagLevArray args = ( (( __fn_dyn1 == global::haxe.lang.Runtime.undefined )) ? (((global::maglev.MagLevArray) (((object) (__fn_float1) )) )) : (((global::maglev.MagLevArray) (__fn_dyn1) )) );
				global::maglev.MagLevArray data = global::maglev.MagLevArray.create();
				#line 54 "/my-component/src/invoices/Invoices.hx"
				data.push(global::maglev.MagLevString.fromString("_not_implemented_"));
				data.push(global::maglev.MagLevString.fromString("Invoices.GetInvoiceSummary"));
				#line 56 "/my-component/src/invoices/Invoices.hx"
				data.push(global::maglev.MagLevString.fromString("invoices"));
				this.bus.call("MindPowered.Telemetry.Send", data);
				#line 58 "/my-component/src/invoices/Invoices.hx"
				global::maglev.MagLevError err = global::maglev.MagLevError.create(-20000, "You are trying to use the \'Invoices.GetInvoiceSummary\' method but it\'s not quite done yet. Please email support@mindpowered.dev to find out when it will be done.", data);
				global::maglev.MagLevResult result = global::maglev.MagLevResult.fromError(err);
				#line 60 "/my-component/src/invoices/Invoices.hx"
				return result;
			}
			#line default
		}
		
		
		public global::maglev.MagLev bus;
		
	}
}



#pragma warning disable 109, 114, 219, 429, 168, 162
namespace invoices {
	public class Invoices_registerMyMethods_63__Fun : global::haxe.lang.Function {
		
		public Invoices_registerMyMethods_63__Fun(global::maglev.MagLev bus) : base(1, 0) {
			#line 63 "/my-component/src/invoices/Invoices.hx"
			this.bus = bus;
		}
		#line default
		
		public override object __hx_invoke1_o(double __fn_float1, object __fn_dyn1) {
			unchecked {
				#line 63 "/my-component/src/invoices/Invoices.hx"
				global::maglev.MagLevArray args = ( (( __fn_dyn1 == global::haxe.lang.Runtime.undefined )) ? (((global::maglev.MagLevArray) (((object) (__fn_float1) )) )) : (((global::maglev.MagLevArray) (__fn_dyn1) )) );
				global::maglev.MagLevArray data = global::maglev.MagLevArray.create();
				#line 65 "/my-component/src/invoices/Invoices.hx"
				data.push(global::maglev.MagLevString.fromString("_not_implemented_"));
				data.push(global::maglev.MagLevString.fromString("Invoices.GetLineItems"));
				#line 67 "/my-component/src/invoices/Invoices.hx"
				data.push(global::maglev.MagLevString.fromString("invoices"));
				this.bus.call("MindPowered.Telemetry.Send", data);
				#line 69 "/my-component/src/invoices/Invoices.hx"
				global::maglev.MagLevError err = global::maglev.MagLevError.create(-20000, "You are trying to use the \'Invoices.GetLineItems\' method but it\'s not quite done yet. Please email support@mindpowered.dev to find out when it will be done.", data);
				global::maglev.MagLevResult result = global::maglev.MagLevResult.fromError(err);
				#line 71 "/my-component/src/invoices/Invoices.hx"
				return result;
			}
			#line default
		}
		
		
		public global::maglev.MagLev bus;
		
	}
}



#pragma warning disable 109, 114, 219, 429, 168, 162
namespace invoices {
	public class Invoices_registerMyMethods_74__Fun : global::haxe.lang.Function {
		
		public Invoices_registerMyMethods_74__Fun(global::maglev.MagLev bus) : base(1, 0) {
			#line 74 "/my-component/src/invoices/Invoices.hx"
			this.bus = bus;
		}
		#line default
		
		public override object __hx_invoke1_o(double __fn_float1, object __fn_dyn1) {
			unchecked {
				#line 74 "/my-component/src/invoices/Invoices.hx"
				global::maglev.MagLevArray args = ( (( __fn_dyn1 == global::haxe.lang.Runtime.undefined )) ? (((global::maglev.MagLevArray) (((object) (__fn_float1) )) )) : (((global::maglev.MagLevArray) (__fn_dyn1) )) );
				global::maglev.MagLevArray data = global::maglev.MagLevArray.create();
				#line 76 "/my-component/src/invoices/Invoices.hx"
				data.push(global::maglev.MagLevString.fromString("_not_implemented_"));
				data.push(global::maglev.MagLevString.fromString("Invoices.AddLineItem"));
				#line 78 "/my-component/src/invoices/Invoices.hx"
				data.push(global::maglev.MagLevString.fromString("invoices"));
				this.bus.call("MindPowered.Telemetry.Send", data);
				#line 80 "/my-component/src/invoices/Invoices.hx"
				global::maglev.MagLevError err = global::maglev.MagLevError.create(-20000, "You are trying to use the \'Invoices.AddLineItem\' method but it\'s not quite done yet. Please email support@mindpowered.dev to find out when it will be done.", data);
				global::maglev.MagLevResult result = global::maglev.MagLevResult.fromError(err);
				#line 82 "/my-component/src/invoices/Invoices.hx"
				return result;
			}
			#line default
		}
		
		
		public global::maglev.MagLev bus;
		
	}
}



#pragma warning disable 109, 114, 219, 429, 168, 162
namespace invoices {
	public class Invoices_registerMyMethods_85__Fun : global::haxe.lang.Function {
		
		public Invoices_registerMyMethods_85__Fun(global::maglev.MagLev bus) : base(1, 0) {
			#line 85 "/my-component/src/invoices/Invoices.hx"
			this.bus = bus;
		}
		#line default
		
		public override object __hx_invoke1_o(double __fn_float1, object __fn_dyn1) {
			unchecked {
				#line 85 "/my-component/src/invoices/Invoices.hx"
				global::maglev.MagLevArray args = ( (( __fn_dyn1 == global::haxe.lang.Runtime.undefined )) ? (((global::maglev.MagLevArray) (((object) (__fn_float1) )) )) : (((global::maglev.MagLevArray) (__fn_dyn1) )) );
				global::maglev.MagLevArray data = global::maglev.MagLevArray.create();
				#line 87 "/my-component/src/invoices/Invoices.hx"
				data.push(global::maglev.MagLevString.fromString("_not_implemented_"));
				data.push(global::maglev.MagLevString.fromString("Invoices.ChangeLineItem"));
				#line 89 "/my-component/src/invoices/Invoices.hx"
				data.push(global::maglev.MagLevString.fromString("invoices"));
				this.bus.call("MindPowered.Telemetry.Send", data);
				#line 91 "/my-component/src/invoices/Invoices.hx"
				global::maglev.MagLevError err = global::maglev.MagLevError.create(-20000, "You are trying to use the \'Invoices.ChangeLineItem\' method but it\'s not quite done yet. Please email support@mindpowered.dev to find out when it will be done.", data);
				global::maglev.MagLevResult result = global::maglev.MagLevResult.fromError(err);
				#line 93 "/my-component/src/invoices/Invoices.hx"
				return result;
			}
			#line default
		}
		
		
		public global::maglev.MagLev bus;
		
	}
}



#pragma warning disable 109, 114, 219, 429, 168, 162
namespace invoices {
	public class Invoices_registerMyMethods_96__Fun : global::haxe.lang.Function {
		
		public Invoices_registerMyMethods_96__Fun(global::maglev.MagLev bus) : base(1, 0) {
			#line 96 "/my-component/src/invoices/Invoices.hx"
			this.bus = bus;
		}
		#line default
		
		public override object __hx_invoke1_o(double __fn_float1, object __fn_dyn1) {
			unchecked {
				#line 96 "/my-component/src/invoices/Invoices.hx"
				global::maglev.MagLevArray args = ( (( __fn_dyn1 == global::haxe.lang.Runtime.undefined )) ? (((global::maglev.MagLevArray) (((object) (__fn_float1) )) )) : (((global::maglev.MagLevArray) (__fn_dyn1) )) );
				global::maglev.MagLevArray data = global::maglev.MagLevArray.create();
				#line 98 "/my-component/src/invoices/Invoices.hx"
				data.push(global::maglev.MagLevString.fromString("_not_implemented_"));
				data.push(global::maglev.MagLevString.fromString("Invoices.RemoveLineItem"));
				#line 100 "/my-component/src/invoices/Invoices.hx"
				data.push(global::maglev.MagLevString.fromString("invoices"));
				this.bus.call("MindPowered.Telemetry.Send", data);
				#line 102 "/my-component/src/invoices/Invoices.hx"
				global::maglev.MagLevError err = global::maglev.MagLevError.create(-20000, "You are trying to use the \'Invoices.RemoveLineItem\' method but it\'s not quite done yet. Please email support@mindpowered.dev to find out when it will be done.", data);
				global::maglev.MagLevResult result = global::maglev.MagLevResult.fromError(err);
				#line 104 "/my-component/src/invoices/Invoices.hx"
				return result;
			}
			#line default
		}
		
		
		public global::maglev.MagLev bus;
		
	}
}



#pragma warning disable 109, 114, 219, 429, 168, 162
namespace invoices {
	public class Invoices_registerMyMethods_107__Fun : global::haxe.lang.Function {
		
		public Invoices_registerMyMethods_107__Fun(global::maglev.MagLev bus) : base(1, 0) {
			#line 107 "/my-component/src/invoices/Invoices.hx"
			this.bus = bus;
		}
		#line default
		
		public override object __hx_invoke1_o(double __fn_float1, object __fn_dyn1) {
			unchecked {
				#line 107 "/my-component/src/invoices/Invoices.hx"
				global::maglev.MagLevArray args = ( (( __fn_dyn1 == global::haxe.lang.Runtime.undefined )) ? (((global::maglev.MagLevArray) (((object) (__fn_float1) )) )) : (((global::maglev.MagLevArray) (__fn_dyn1) )) );
				global::maglev.MagLevArray data = global::maglev.MagLevArray.create();
				#line 109 "/my-component/src/invoices/Invoices.hx"
				data.push(global::maglev.MagLevString.fromString("_not_implemented_"));
				data.push(global::maglev.MagLevString.fromString("Invoices.GetInvoicesByClient"));
				#line 111 "/my-component/src/invoices/Invoices.hx"
				data.push(global::maglev.MagLevString.fromString("invoices"));
				this.bus.call("MindPowered.Telemetry.Send", data);
				#line 113 "/my-component/src/invoices/Invoices.hx"
				global::maglev.MagLevError err = global::maglev.MagLevError.create(-20000, "You are trying to use the \'Invoices.GetInvoicesByClient\' method but it\'s not quite done yet. Please email support@mindpowered.dev to find out when it will be done.", data);
				global::maglev.MagLevResult result = global::maglev.MagLevResult.fromError(err);
				#line 115 "/my-component/src/invoices/Invoices.hx"
				return result;
			}
			#line default
		}
		
		
		public global::maglev.MagLev bus;
		
	}
}



#pragma warning disable 109, 114, 219, 429, 168, 162
namespace invoices {
	public class Invoices_registerMyMethods_118__Fun : global::haxe.lang.Function {
		
		public Invoices_registerMyMethods_118__Fun(global::maglev.MagLev bus) : base(1, 0) {
			#line 118 "/my-component/src/invoices/Invoices.hx"
			this.bus = bus;
		}
		#line default
		
		public override object __hx_invoke1_o(double __fn_float1, object __fn_dyn1) {
			unchecked {
				#line 118 "/my-component/src/invoices/Invoices.hx"
				global::maglev.MagLevArray args = ( (( __fn_dyn1 == global::haxe.lang.Runtime.undefined )) ? (((global::maglev.MagLevArray) (((object) (__fn_float1) )) )) : (((global::maglev.MagLevArray) (__fn_dyn1) )) );
				global::maglev.MagLevArray data = global::maglev.MagLevArray.create();
				#line 120 "/my-component/src/invoices/Invoices.hx"
				data.push(global::maglev.MagLevString.fromString("_not_implemented_"));
				data.push(global::maglev.MagLevString.fromString("Invoices.GetAllInvoices"));
				#line 122 "/my-component/src/invoices/Invoices.hx"
				data.push(global::maglev.MagLevString.fromString("invoices"));
				this.bus.call("MindPowered.Telemetry.Send", data);
				#line 124 "/my-component/src/invoices/Invoices.hx"
				global::maglev.MagLevError err = global::maglev.MagLevError.create(-20000, "You are trying to use the \'Invoices.GetAllInvoices\' method but it\'s not quite done yet. Please email support@mindpowered.dev to find out when it will be done.", data);
				global::maglev.MagLevResult result = global::maglev.MagLevResult.fromError(err);
				#line 126 "/my-component/src/invoices/Invoices.hx"
				return result;
			}
			#line default
		}
		
		
		public global::maglev.MagLev bus;
		
	}
}



#pragma warning disable 109, 114, 219, 429, 168, 162
namespace invoices {
	public class Invoices_registerMyMethods_129__Fun : global::haxe.lang.Function {
		
		public Invoices_registerMyMethods_129__Fun(global::maglev.MagLev bus) : base(1, 0) {
			#line 129 "/my-component/src/invoices/Invoices.hx"
			this.bus = bus;
		}
		#line default
		
		public override object __hx_invoke1_o(double __fn_float1, object __fn_dyn1) {
			unchecked {
				#line 129 "/my-component/src/invoices/Invoices.hx"
				global::maglev.MagLevArray args = ( (( __fn_dyn1 == global::haxe.lang.Runtime.undefined )) ? (((global::maglev.MagLevArray) (((object) (__fn_float1) )) )) : (((global::maglev.MagLevArray) (__fn_dyn1) )) );
				global::maglev.MagLevArray data = global::maglev.MagLevArray.create();
				#line 131 "/my-component/src/invoices/Invoices.hx"
				data.push(global::maglev.MagLevString.fromString("_not_implemented_"));
				data.push(global::maglev.MagLevString.fromString("Invoices.FindInvoiceByNumber"));
				#line 133 "/my-component/src/invoices/Invoices.hx"
				data.push(global::maglev.MagLevString.fromString("invoices"));
				this.bus.call("MindPowered.Telemetry.Send", data);
				#line 135 "/my-component/src/invoices/Invoices.hx"
				global::maglev.MagLevError err = global::maglev.MagLevError.create(-20000, "You are trying to use the \'Invoices.FindInvoiceByNumber\' method but it\'s not quite done yet. Please email support@mindpowered.dev to find out when it will be done.", data);
				global::maglev.MagLevResult result = global::maglev.MagLevResult.fromError(err);
				#line 137 "/my-component/src/invoices/Invoices.hx"
				return result;
			}
			#line default
		}
		
		
		public global::maglev.MagLev bus;
		
	}
}


